/**
 * The admin audit action vocabulary. `AdminAuditLog.action` itself stays
 * plain text in Postgres (see the model's own doc comment in
 * schema.prisma) — this TypeScript union is where compile-time safety
 * actually lives, mirroring DomainEventType's own relationship to
 * DomainEvent.type. Grows as later H11 stages add mutating admin
 * endpoints; a typo'd action fails the build rather than silently writing
 * an unrecognized string into the audit table.
 */
export type AdminAuditAction =
  | "admin_user.created"
  | "admin_user.role_changed"
  | "admin_user.suspended"
  | "admin_user.reactivated"
  | "support_case.created"
  | "support_case.assigned"
  | "support_case.status_changed"
  | "support_message.posted"
  | "internal_note.added"
  | "admin_task.created"
  | "admin_task.completed"
  | "dispute.opened"
  | "dispute.evidence_added"
  | "dispute.status_changed"
  | "trust_case.opened"
  | "trust_case.assigned"
  | "trust_case.status_changed"
  | "trust_action.taken"
  | "appeal.submitted"
  | "appeal.resolved"
  | "admin_refund_approval.requested"
  | "admin_refund_approval.approved"
  | "admin_refund_approval.rejected"
  | "admin_refund_approval.executed"
  | "verification.status_changed"
  | "pii.revealed"
  | "seller_settlement.calculated"
  | "seller_settlement.approved"
  | "seller_settlement.paid"
  | "seller_settlement.cancelled"
  | "seller_settlement.failed"
  | "seller_adjustment.created"
  | "marketplace_settlement.imported"
  | "marketplace_reconciliation.resolved"
  | "article.created"
  | "article.updated"
  | "article.published"
  | "article.hidden"
  | "article.archived"
  | "article.restored"
  | "category.created"
  | "category.updated"
  | "tag.created"
  | "tag.updated"
  | "content_author.created"
  | "content_author.updated"
  | "media_asset.uploaded"
  | "media_asset.disabled"
  | "content_placement.updated"
  | "subscription_plan.created"
  | "subscription_plan.updated"
  | "subscription_plan_price.created"
  | "subscription_plan_price.updated"
  | "subscription.admin_cancelled"
  | "subscription.billing_attempt_refunded"
  | "subscription_entitlement_override.granted"
  | "subscription_entitlement_override.revoked"
  | "animal_support_organization.created"
  | "animal_support_organization.updated"
  | "animal_support_organization.verification_changed"
  | "animal_support_organization.listed_changed"
  | "rescue_case.created"
  | "rescue_case.status_changed"
  | "support_campaign.created"
  | "support_campaign.status_changed"
  | "support_campaign.update_posted"
  | "donation.payout_recorded"
  | "donation.refunded"
  | "community_report.escalated"
  | "community_report.dismissed";
