import type { AppLocale } from "@/lib/i18n/config";
const fa = {
  title: "زندگی با آن‌ها،\nمنظم حول خودشان.",
  intro: "سلامت، مراقبت و زندگی روزمره؛\nهمه در یک سیستم.",
  start: "شروع کنید",
  signIn: "ورود",
  explore: "دنیای PET LIFE را کشف کنید",
  pet: "حیوان شما",
  breed: "اشپیتز",
  language: "زبان",
  theme: "ظاهر",
  destinations: "مقصد در این دنیا",
  overview: "نمای کلی",
  next: "بعدی",
  previous: "قبلی",
  pause: "کاهش حرکت",
  hint: "با اسکرول، لمس یا کلیدهای جهت در دنیا حرکت کنید.",
  demo: "نمایش داستانی؛ اطلاعات سلامت واقعی نیست.",
  future: "این تجربه در مسیر ساخت است.",
  back: "بازگشت به دنیا",
  skip: "رفتن به کنترل‌های دنیا",
  contexts: [
    [
      "نمای کلی",
      "زندگی با آن‌ها،\nمنظم حول خودشان.",
      "سلامت، مراقبت و زندگی روزمره؛\nهمه در یک سیستم.",
      "شروع کنید",
    ],
    ["حیوان شما", "همه‌چیز از حیوان شما شروع می‌شود.", "یک هویت، در تمام این دنیا.", "شناخت حیوان من"],
    [
      "سلامت",
      "سلامت حیوان شما",
      "دانسته‌ها و اطلاعات ثبت‌نشده، هر دو روشن‌اند. نامشخص بودن به معنای سلامت نیست.",
      "بررسی سلامت",
    ],
    [
      "دامپزشک",
      "مراقبت دامپزشکی برای حیوان شما",
      "اطلاعات مرتبط، با اجازهٔ شما و برای زمان لازم به اشتراک گذاشته می‌شود.",
      "پیدا کردن دامپزشک",
    ],
    ["مراقبت", "مراقبت برای حیوان شما", "مراقبت روزمره، با توجه به زمینه و برنامهٔ ثبت‌شده.", "پیدا کردن مراقبت"],
    ["خرید", "برای حیوان شما", "محصول‌هایی متناسب‌تر با اطلاعات ثبت‌شده؛ شناخت، پیش از خرید.", "مشاهده محصولات"],
    [
      "آراستگی",
      "رسیدگی، بخشی از زندگی است.",
      "خدمت مناسب را با توجه به نیاز واقعی و انتخاب شما پیدا کنید.",
      "پیدا کردن خدمات",
    ],
    ["رفت‌وآمد", "در مسیر، کنار حیوان شما", "رفت‌وآمد هم ادامهٔ همان مسیر مراقبت است.", "دیدن خدمات"],
    ["سفر", "سفر با حیوان شما", "مدارک، آمادگی و مسیر سفر؛ چشم‌اندازی برای یک جریان متصل.", "بازگشت به دنیا"],
    [
      "حمایت",
      "دنیایی که مراقب است.",
      "حمایت از حیوانات و پناهگاه‌ها؛ بخشی از آیندهٔ این دنیا.",
      "بازگشت به دنیا",
    ],
    [
      "خاطرات",
      "بخشی از زندگی با حیوان شما",
      "بعضی چیزها فقط برنامه و مراقبت نیستند؛ لحظه‌هایی‌اند که می‌مانند.",
      "بازگشت به دنیا",
    ],
    ["دوباره در کنار هم", "یک زندگی؛ یک دنیای متصل.", "از هویت حیوانتان شروع کنید.", "شروع کنید"],
  ],
};
const en = {
  title: "Life with them,\norganized around who they are.",
  intro: "Health, care and everyday life —\nconnected in one system.",
  start: "Get Started",
  signIn: "Sign in",
  explore: "Explore PET LIFE",
  pet: "Your pet",
  breed: "Spitz",
  language: "Language",
  theme: "Appearance",
  destinations: "Destination in this world",
  overview: "Overview",
  next: "Next",
  previous: "Previous",
  pause: "Reduce motion",
  hint: "Explore with scroll, swipe or arrow keys.",
  demo: "Illustrative story; not a real health record.",
  future: "This experience is in development.",
  back: "Back to the world",
  skip: "Skip to world controls",
  contexts: [
    [
      "Overview",
      "Life with them,\norganized around who they are.",
      "Health, care and everyday life —\nconnected in one system.",
      "Get Started",
    ],
    [
      "Your pet",
      "Everything starts with your pet.",
      ". One identity throughout this living world.",
      "Meet my pet",
    ],
    [
      "Health",
      "Your pet's health",
      "Keep known facts and missing information visible. Unknown does not mean healthy.",
      "Explore health",
    ],
    [
      "Vet",
      "Veterinary care for your pet",
      "Share relevant context with your permission, for the time it is needed.",
      "Find a vet",
    ],
    [
      "Care",
      "Care around your pet",
      "Everyday care, informed by the context and routine you provide.",
      "Find care",
    ],
    [
      "Shop",
      "For your pet",
      "More relevant products, grounded in recorded information. Context before purchase.",
      "Explore products",
    ],
    [
      "Grooming",
      "Care in the everyday",
      "Find a service around actual needs and your choices.",
      "Find services",
    ],
    [
      "Mobility",
      "Along for the journey",
      "Getting there is part of the same care journey.",
      "Explore services",
    ],
    [
      "Travel",
      "Travel with your pet",
      "Documents, preparation and the journey — a vision for one connected flow.",
      "Back to the world",
    ],
    [
      "Support",
      "A world that cares",
      "Animal welfare and shelters are part of this world's future.",
      "Back to the world",
    ],
    [
      "Memories",
      "Life with your pet",
      "Some things are more than routines and care. They are the moments that stay.",
      "Back to the world",
    ],
    ["Reconnect", "One life. One connected world.", "Start with your pet's identity.", "Get Started"],
  ],
};
export const landingCopy: Record<AppLocale, typeof en> = { en, fa };
