"use client";
import { useEffect, useState } from "react";
import { Button, ContextSurface, EmptyState, ErrorRecovery, Skeleton, StatusLabel } from "@petlife/ui";
import { InsuranceVerificationStatus, type InsuranceProductDto, type InsuranceProviderDto } from "@petlife/types";
import { ApiError } from "@/lib/api/client";
import { adminService } from "@/services/admin.service";

export function AdminInsuranceView() {
  const [providers, setProviders] = useState<InsuranceProviderDto[] | null>(null); const [products, setProducts] = useState<InsuranceProductDto[] | null>(null); const [error, setError] = useState<string | null>(null);
  async function load() { try { const [providerResult, productResult] = await Promise.all([adminService.listInsuranceProviders({ pageSize: 100 }), adminService.listInsuranceProducts({ pageSize: 100 })]); setProviders(providerResult.items); setProducts(productResult.items); } catch (err) { setError(err instanceof ApiError ? err.message : "Insurance operations could not be loaded."); } }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load(); }, []);
  if (error && !providers) return <ErrorRecovery title="Insurance operations" message={error} retryLabel="Try again" onRetry={load} />;
  if (!providers || !products) return <Skeleton className="h-64 w-full" aria-label="Insurance operations" />;
  return <div className="flex flex-col gap-6"><header><h1 className="text-page-title text-text-primary">Insurance operations</h1><p className="text-body text-text-secondary">Moderate existing insurance providers and products. Publishing remains an explicit admin decision.</p></header>{error ? <p className="text-body text-state-urgent">{error}</p> : null}<section className="space-y-3"><h2 className="text-section-title text-text-primary">Providers</h2>{providers.length ? providers.map((item) => <ContextSurface key={item.id} className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-body font-semibold text-text-primary">{item.name}</p><p className="text-metadata text-text-secondary">{item.country}</p></div><div className="flex flex-wrap items-center gap-2"><StatusLabel tone={item.status === InsuranceVerificationStatus.VERIFIED ? "success" : "neutral"}>{item.status}</StatusLabel><Button size="sm" variant="secondary" onClick={() => void adminService.setInsuranceProviderVerification(item.id, InsuranceVerificationStatus.VERIFIED).then(load)}>{item.status === InsuranceVerificationStatus.VERIFIED ? "Verified" : "Verify"}</Button><Button size="sm" variant="ghost" onClick={() => void adminService.setInsuranceProviderListed(item.id, !item.isPubliclyListed).then(load)}>{item.isPubliclyListed ? "Unlist" : "List"}</Button></div></ContextSurface>) : <EmptyState title="No insurance providers" />}</section><section className="space-y-3"><h2 className="text-section-title text-text-primary">Products</h2>{products.length ? products.map((item) => <ContextSurface key={item.id} className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-body font-semibold text-text-primary">{item.name}</p><p className="text-metadata text-text-secondary">{item.providerName} · {item.country}</p></div><div className="flex flex-wrap items-center gap-2"><StatusLabel tone={item.status === InsuranceVerificationStatus.VERIFIED ? "success" : "neutral"}>{item.status}</StatusLabel><Button size="sm" variant="secondary" onClick={() => void adminService.setInsuranceProductVerification(item.id, InsuranceVerificationStatus.VERIFIED).then(load)}>Verify</Button><Button size="sm" variant="ghost" onClick={() => void adminService.setInsuranceProductListed(item.id, !item.isPubliclyListed).then(load)}>{item.isPubliclyListed ? "Unlist" : "List"}</Button></div></ContextSurface>) : <EmptyState title="No insurance products" />}</section></div>;
}
