"use client";
import { useCallback, useEffect, useState } from "react";
import { useLocale } from "next-intl";
import { useRouter } from "next/navigation";
import { Avatar, Button, ContextSurface, Dialog, EmptyState, Input, Select, Skeleton, StatusLabel } from "@petlife/ui";
import type { PetAccessFlags, PetDto } from "@petlife/types";
import { householdsService } from "@/services/households.service";
import { petsService, type ManagedPetAccessGrant } from "@/services/pets.service";
import type { HouseholdCollaborationDto } from "@/services/account.service";
import { AccountPageHeader } from "./AccountNav";
import { ConfirmActionDialog } from "./ConfirmActionDialog";
import { ApiError } from "@/lib/api/client";

const VIEW_ONLY: PetAccessFlags={canViewIdentity:true,canEditIdentity:false,canViewHealth:false,canEditHealth:false,canBookCare:false,canViewCareProfile:true,canEditCareProfile:false,canViewLocation:false,canManageAccess:false,canRecordClinicalData:false};
const CARE_HELPER: PetAccessFlags={canViewIdentity:true,canEditIdentity:false,canViewHealth:true,canEditHealth:false,canBookCare:true,canViewCareProfile:true,canEditCareProfile:true,canViewLocation:true,canManageAccess:false,canRecordClinicalData:false};
const FULL: PetAccessFlags={canViewIdentity:true,canEditIdentity:true,canViewHealth:true,canEditHealth:true,canBookCare:true,canViewCareProfile:true,canEditCareProfile:true,canViewLocation:true,canManageAccess:false,canRecordClinicalData:false};
const PRESETS={VIEW_ONLY,CARE_HELPER,FULL};
const FLAGS: Array<[keyof PetAccessFlags,string,string]>=[["canViewIdentity","مشاهده مشخصات","View basic profile"],["canEditIdentity","ویرایش مشخصات","Edit identity"],["canViewHealth","مشاهده سلامت","View health"],["canEditHealth","ویرایش سلامت","Edit health"],["canBookCare","مدیریت رزرو","Manage bookings"],["canViewCareProfile","مشاهده مراقبت","View care"],["canEditCareProfile","ویرایش مراقبت","Edit care"],["canViewLocation","مشاهده موقعیت","View location"],["canManageAccess","مدیریت دسترسی","Manage access"]];

export function PetAccessView({petId}:{petId:string}) {
 const locale=useLocale(); const router=useRouter(); const [pet,setPet]=useState<PetDto|null>(null); const [home,setHome]=useState<HouseholdCollaborationDto|null>(null); const [grants,setGrants]=useState<ManagedPetAccessGrant[]|null>(null); const [loadError,setLoadError]=useState(false); const [open,setOpen]=useState(false); const [userId,setUserId]=useState(""); const [preset,setPreset]=useState<keyof typeof PRESETS>("VIEW_ONLY"); const [expiresAt,setExpiresAt]=useState(""); const [reason,setReason]=useState(""); const [busy,setBusy]=useState(false);
 const [revoking,setRevoking]=useState<ManagedPetAccessGrant|null>(null);
 const [actionError,setActionError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoadError(false);try{const nextPet=await petsService.getById(petId); const [nextHome,nextGrants]=await Promise.all([householdsService.collaboration(nextPet.householdId),petsService.listAccessGrants(petId)]); setPet(nextPet);setHome(nextHome);setGrants(nextGrants);setUserId((v)=>v||nextHome.members.find((m)=>m.role!=="OWNER")?.userId||"");}catch{setLoadError(true)}},[petId]);
 useEffect(()=>{void load()},[load]);
 async function create(){if(!userId)return;setBusy(true);setActionError(null);try{await petsService.createAccessGrant(petId,{userId,...PRESETS[preset],...(expiresAt?{expiresAt:new Date(expiresAt).toISOString()}:{}),reason:reason||undefined});setOpen(false);setExpiresAt("");setReason("");await load()}catch(e){setActionError(e instanceof ApiError?e.message:(locale==="fa"?"انجام نشد.":"That didn't work."))}finally{setBusy(false)}}
 async function update(grant:ManagedPetAccessGrant,next:keyof typeof PRESETS){setBusy(true);try{await petsService.updateAccessGrant(petId,grant.id,PRESETS[next]);await load()}finally{setBusy(false)}}
 if(loadError)return <div className="account-stack"><AccountPageHeader eyebrow={locale==="fa"?"مجوزهای حیوان":"PET PERMISSIONS"} title={locale==="fa"?"دسترسی ممکن نیست":"Access unavailable"} description={locale==="fa"?"این حساب اجازهٔ مدیریت مجوزهای این حیوان را ندارد.":"This account cannot manage permissions for this pet."}/><EmptyState title={locale==="fa"?"مجوز مدیریت ندارید":"You do not have management access"} description={locale==="fa"?"از مدیر اصلی خانواده بخواهید دسترسی شما را بررسی کند.":"Ask the household organizer to review your access."} actionLabel={locale==="fa"?"بازگشت به خانواده":"Back to household"} onAction={()=>router.push(`/${locale}/profile/household`)}/></div>;
 if(!pet||!home||!grants)return <Skeleton className="h-96 w-full" aria-label={locale==="fa"?"در حال بارگذاری":"Loading"}/>;
 const candidates=home.members.filter((m)=>m.role!=="OWNER");
 return <div className="account-stack"><AccountPageHeader eyebrow={locale==="fa"?"مجوزهای حیوان":"PET PERMISSIONS"} title={locale==="fa"?`دسترسی به ${pet.name}`:`Access to ${pet.name}`} description={locale==="fa"?"اطلاعات پزشکی و خصوصی فقط در محدودهٔ مجوزهای روشن و قابل لغو در دسترس است.":"Private and medical data is available only through explicit, revocable permissions."}/>
 <ContextSurface className="permission-principle"><b>{locale==="fa"?"عضویت خانواده ≠ دسترسی کامل":"Household membership ≠ full access"}</b><p>{locale==="fa"?"انقضای دسترسی در بک‌اند اجرا می‌شود و فقط یک برچسب ظاهری نیست.":"Expiry is enforced by backend authorization, not only shown in the interface."}</p><Button onClick={()=>setOpen(true)} disabled={!candidates.length}>{locale==="fa"?"ایجاد دسترسی":"Create access"}</Button></ContextSurface>
 <section><div className="account-section-title"><h2>{locale==="fa"?"دسترسی‌های ثبت‌شده":"Recorded grants"}</h2></div><div className="permission-grants">{grants.map((grant)=><ContextSurface key={grant.id} className={!grant.active?"opacity-60":""}><div className="permission-grant-head"><div className="flex items-center gap-3"><Avatar name={grant.user.displayName} src={grant.user.avatarUrl} size="sm"/><div><b>{grant.user.displayName}</b><p>{grant.source==="TEMPORARY"?(locale==="fa"?"دسترسی موقت":"Temporary access"):(locale==="fa"?"دسترسی خانوادگی":"Household access")}</p></div></div><StatusLabel tone={grant.active?"success":"neutral"}>{grant.active?(locale==="fa"?"فعال":"Active"):(locale==="fa"?"پایان‌یافته":"Ended")}</StatusLabel></div>{grant.expiresAt&&<p className="permission-expiry">{locale==="fa"?"دسترسی تا":"Access until"} {new Intl.DateTimeFormat(locale,{dateStyle:"long",timeStyle:"short"}).format(new Date(grant.expiresAt))}</p>}<div className="permission-chip-list">{FLAGS.filter(([key])=>grant[key]).map(([key,fa,en])=><span key={key}>{locale==="fa"?fa:en}</span>)}</div>{grant.active&&grant.source!=="HOUSEHOLD"&&<div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" disabled={busy} onClick={()=>update(grant,"VIEW_ONLY")}>{locale==="fa"?"فقط مشاهده":"View only"}</Button><Button size="sm" variant="secondary" disabled={busy} onClick={()=>update(grant,"CARE_HELPER")}>{locale==="fa"?"همیار مراقبت":"Care helper"}</Button><Button size="sm" variant="ghost" disabled={busy} onClick={()=>setRevoking(grant)}>{locale==="fa"?"لغو زودهنگام":"Revoke early"}</Button></div>}</ContextSurface>)}</div></section>
 <Dialog open={open} onClose={()=>setOpen(false)} title={locale==="fa"?"دسترسی جدید":"New access"}><div className="flex flex-col gap-4"><Select label={locale==="fa"?"عضو":"Member"} value={userId} onChange={(e)=>setUserId(e.target.value)} options={candidates.map((m)=>({value:m.userId,label:m.user.displayName}))}/><Select label={locale==="fa"?"سطح دسترسی":"Access preset"} value={preset} onChange={(e)=>setPreset(e.target.value as keyof typeof PRESETS)} options={[{value:"VIEW_ONLY",label:locale==="fa"?"فقط مشاهده":"View only"},{value:"CARE_HELPER",label:locale==="fa"?"همیار مراقبت":"Care helper"},{value:"FULL",label:locale==="fa"?"دسترسی کامل خانوادگی":"Full household access"}]}/><div className="permission-chip-list">{FLAGS.filter(([key])=>PRESETS[preset][key]).map(([key,fa,en])=><span key={key}>{locale==="fa"?fa:en}</span>)}</div><Input label={locale==="fa"?"زمان انقضا (اختیاری)":"Expiry (optional)"} type="datetime-local" value={expiresAt} onChange={(e)=>setExpiresAt(e.target.value)}/><Input label={locale==="fa"?"دلیل یا زمینه (اختیاری)":"Reason or context (optional)"} value={reason} onChange={(e)=>setReason(e.target.value)}/><div className="flex gap-2"><Button isLoading={busy} onClick={create}>{locale==="fa"?"ثبت دسترسی":"Grant access"}</Button><Button variant="ghost" onClick={()=>setOpen(false)}>{locale==="fa"?"انصراف":"Cancel"}</Button></div></div></Dialog>
 {actionError&&<p role="alert" className="text-body text-state-urgent">{actionError}</p>}
 {revoking&&<ConfirmActionDialog open onClose={()=>setRevoking(null)} title={locale==="fa"?"لغو این دسترسی":"Revoke this access"} consequences={[locale==="fa"?"این دسترسی فوراً در سرور پایان می‌یابد و صفحه‌های حیوان برای او بسته می‌شود.":"This access ends on the server immediately and the pet's pages close for them.",locale==="fa"?"او می‌بیند که دسترسی‌اش لغو شده است.":"They'll see that their access was revoked."]} keeps={[locale==="fa"?"سابقهٔ این دسترسی در تاریخچه می‌ماند.":"The grant stays in the access history."]} confirmLabel={locale==="fa"?"لغو دسترسی":"Revoke access"} onConfirm={async()=>{await petsService.revokeAccessGrant(petId,revoking.id);await load()}}/>}</div>
}
