"use client";
import { useEffect, useState } from "react";
import { useLocale } from "next-intl";
import { useRouter } from "next/navigation";
import { Button, ContextSurface, Dialog, Input, Skeleton, StatusLabel } from "@petlife/ui";
import type { PetDto } from "@petlife/types";
import { petsService } from "@/services/pets.service";
import { AccountPageHeader } from "./AccountNav";
import { useStatusText } from "@/lib/status/use-status-text";

export function PetLifecycleView({petId}:{petId:string}) {
  const statusText = useStatusText();
 const locale=useLocale(); const router=useRouter(); const [pet,setPet]=useState<PetDto|null>(null); const [action,setAction]=useState<"deceased"|"memorial"|null>(null); const [reason,setReason]=useState(""); const [busy,setBusy]=useState(false);
 useEffect(()=>{void petsService.getById(petId).then(setPet)},[petId]);
 async function confirm(){if(!pet||!action)return;setBusy(true);try{const updated=action==="deceased"?await petsService.markDeceased(pet.id,reason||undefined):await petsService.transitionToMemorial(pet.id,reason||undefined);setPet(updated);setAction(null);setReason("")}finally{setBusy(false)}}
 if(!pet)return <Skeleton className="h-80 w-full" aria-label={locale==="fa"?"در حال بارگذاری":"Loading"}/>;
 return <div className="account-stack"><AccountPageHeader eyebrow={locale==="fa"?"وضعیت زندگی":"PET LIFECYCLE"} title={pet.name} description={locale==="fa"?"تغییرهای حساس با تأیید جداگانه ثبت می‌شوند و پرونده سلامت و خاطرات را از بین نمی‌برند.":"Sensitive changes require separate confirmation and never erase health records or memories."}/><ContextSurface className="lifecycle-current"><div><p>{locale==="fa"?"وضعیت فعلی":"Current status"}</p><h2>{statusText.label(pet.lifecycleStatus, "lifecycle")}</h2></div><StatusLabel tone={pet.lifecycleStatus==="ACTIVE"?"success":"neutral"}>{statusText.label(pet.lifecycleStatus, "lifecycle")}</StatusLabel></ContextSurface>
 <section className="lifecycle-actions"><ContextSurface><h2>{locale==="fa"?"گم‌شدن":"Lost pet"}</h2><p>{locale==="fa"?"گم‌شدن یک رخداد عملیاتی با اعلان، گزارش مشاهده و پیگیری است؛ از مسیر اختصاصی انجام می‌شود.":"Lost pet reporting is an operational incident with alerts, sightings and follow-up."}</p><Button variant="secondary" onClick={()=>router.push(`/${locale}/lost-pet/report?petId=${pet.id}`)}>{locale==="fa"?"ورود به گزارش گم‌شدن":"Open lost pet flow"}</Button></ContextSurface><ContextSurface><h2>{locale==="fa"?"فوت و یادبود":"Deceased & memorial"}</h2><p>{locale==="fa"?"وضعیت فوت یک واقعیت حساس است. حالت یادبود پس از آن و با انتخاب جداگانه فعال می‌شود.":"Deceased is a sensitive lifecycle fact. Memorial mode is a separate, later choice."}</p>{pet.lifecycleStatus==="ACTIVE"||pet.lifecycleStatus==="LOST"?<Button variant="secondary" onClick={()=>setAction("deceased")}>{locale==="fa"?"ثبت فوت":"Mark deceased"}</Button>:null}{pet.lifecycleStatus==="DECEASED"?<Button onClick={()=>setAction("memorial")}>{locale==="fa"?"فعال‌سازی یادبود":"Enable memorial"}</Button>:null}</ContextSurface></section>
 <Dialog open={Boolean(action)} onClose={()=>setAction(null)} title={action==="deceased"?(locale==="fa"?"تأیید ثبت فوت":"Confirm deceased status"):(locale==="fa"?"فعال‌سازی حالت یادبود":"Enable memorial mode")}><div className="flex flex-col gap-4"><p className="text-body text-text-secondary">{action==="deceased"?(locale==="fa"?"پرونده پزشکی و خاطرات حفظ می‌شوند و یادآوری‌های مراقبتی باید متوقف شوند. این اقدام عادی و روزمره نیست.":"Medical records and memories remain; care nudges should stop. This is not a routine profile edit."):(locale==="fa"?"حالت یادبود هویت و خاطرات را حفظ می‌کند و مالکیت دائمی را تغییر نمی‌دهد.":"Memorial mode preserves identity and memories and does not change ownership.")}</p><Input label={locale==="fa"?"یادداشت اختیاری":"Optional note"} value={reason} onChange={(e)=>setReason(e.target.value)}/><div className="flex gap-2"><Button variant={action==="deceased"?"danger":"primary"} isLoading={busy} onClick={confirm}>{locale==="fa"?"تأیید نهایی":"Confirm"}</Button><Button variant="ghost" onClick={()=>setAction(null)}>{locale==="fa"?"انصراف":"Cancel"}</Button></div></div></Dialog></div>
}
