"use client";
import { useCallback, useEffect, useState } from "react";
import { useLocale } from "next-intl";
import { Button, ContextSurface, ErrorRecovery, Skeleton, StatusLabel } from "@petlife/ui";
import { PasswordInput } from "@/features/auth/PasswordInput";
import { accountService, type SecurityCenterDto } from "@/services/account.service";
import { authService } from "@/services/auth.service";
import { AccountPageHeader } from "./AccountNav";

function deviceName(agent:string|null,locale:string){if(!agent)return locale==="fa"?"دستگاه ناشناس":"Unknown device";const browser=/Edg\//.test(agent)?"Edge":/Chrome\//.test(agent)?"Chrome":/Firefox\//.test(agent)?"Firefox":/Safari\//.test(agent)?"Safari":locale==="fa"?"مرورگر":"Browser";const os=/Windows/.test(agent)?"Windows":/Android/.test(agent)?"Android":/iPhone|iPad/.test(agent)?"iOS":/Mac OS/.test(agent)?"macOS":"";return[browser,os].filter(Boolean).join(" · ")}

export function SecurityCenterView(){
 const locale=useLocale();const[data,setData]=useState<SecurityCenterDto|null>(null);const[failed,setFailed]=useState(false);const[busy,setBusy]=useState<string|null>(null);const[currentPassword,setCurrentPassword]=useState("");const[newPassword,setNewPassword]=useState("");const[passwordMessage,setPasswordMessage]=useState<string|null>(null);
 const load=useCallback(async()=>{setFailed(false);try{setData(await accountService.security())}catch{setFailed(true)}},[]);useEffect(()=>{void load()},[load]);
 async function revoke(id:string){setBusy(id);try{await accountService.revokeSession(id);await load()}finally{setBusy(null)}}
 async function revokeOthers(){setBusy("others");try{await accountService.revokeOtherSessions();await load()}finally{setBusy(null)}}
 async function changePassword(){setBusy("password");setPasswordMessage(null);try{await authService.setOrChangePassword({currentPassword:currentPassword||undefined,newPassword});setPasswordMessage(locale==="fa"?"رمز تغییر کرد. برای امنیت، دوباره وارد حساب شوید.":"Password changed. Sign in again for security.");setCurrentPassword("");setNewPassword("")}catch{setPasswordMessage(locale==="fa"?"تغییر رمز انجام نشد؛ رمز فعلی یا شرایط رمز جدید را بررسی کنید.":"Could not change password; check the current password and new password requirements.")}finally{setBusy(null)}}
 if(failed)return <ErrorRecovery title={locale==="fa"?"امنیت":"Security"} message="" retryLabel={locale==="fa"?"تلاش دوباره":"Retry"} onRetry={load}/>;
 if(!data)return <Skeleton className="h-96 w-full" aria-label="loading"/>;
 return <div className="account-stack"><AccountPageHeader eyebrow={locale==="fa"?"مرکز امنیت":"SECURITY CENTER"} title={locale==="fa"?"ورودها و دستگاه‌ها":"Sign-ins & devices"} description={locale==="fa"?"روش‌های ورود واقعی و تمام نشست‌های فعال حساب را بررسی کنید.":"Review real sign-in methods and every active account session."}/>
 <section><div className="account-section-title"><h2>{locale==="fa"?"روش‌های ورود":"Sign-in methods"}</h2></div><div className="security-list"><SecurityRow title={locale==="fa"?"موبایل":"Phone"} detail={data.methods.phone.value||(locale==="fa"?"ثبت نشده":"Not added")} active={data.methods.phone.verified} locale={locale}/><SecurityRow title={locale==="fa"?"ایمیل":"Email"} detail={data.methods.email.value||(locale==="fa"?"ثبت نشده":"Not added")} active={data.methods.email.verified} locale={locale}/><SecurityRow title={locale==="fa"?"رمز عبور":"Password"} detail={data.methods.password.connected?(locale==="fa"?"برای ورود در دسترس است":"Available for sign-in"):(locale==="fa"?"هنوز تنظیم نشده":"Not set")} active={data.methods.password.connected} locale={locale}/>{data.methods.providers.map((p)=><SecurityRow key={p.provider} title={p.provider} detail={p.email||""} active locale={locale}/>)}</div></section>
 <ContextSurface className="account-form"><div><h2 className="text-section-title">{data.methods.password.connected?(locale==="fa"?"تغییر رمز عبور":"Change password"):(locale==="fa"?"تنظیم رمز عبور":"Set a password")}</h2><p className="mt-1 text-metadata text-text-secondary">{locale==="fa"?"پس از تغییر رمز، همهٔ نشست‌ها برای حفاظت از حساب باطل می‌شوند.":"After a password change, all sessions are invalidated to protect the account."}</p></div>{data.methods.password.connected&&<PasswordInput label={locale==="fa"?"رمز فعلی":"Current password"} autoComplete="current-password" value={currentPassword} onChange={(e)=>setCurrentPassword(e.target.value)}/>}<PasswordInput label={locale==="fa"?"رمز جدید":"New password"} autoComplete="new-password" value={newPassword} onChange={(e)=>setNewPassword(e.target.value)}/>{passwordMessage&&<p role="status" className="text-metadata text-text-secondary">{passwordMessage}</p>}<Button isLoading={busy==="password"} disabled={newPassword.length<8||(data.methods.password.connected&&!currentPassword)} onClick={changePassword}>{locale==="fa"?"ذخیره رمز":"Save password"}</Button></ContextSurface>
 <section><div className="account-section-title"><div><h2>{locale==="fa"?"نشست‌های فعال":"Active sessions"}</h2><p>{locale==="fa"?"اگر دستگاهی را نمی‌شناسید، دسترسی آن را قطع کنید.":"Sign out any device you do not recognize."}</p></div>{data.sessions.some((s)=>!s.current)&&<Button variant="secondary" size="sm" isLoading={busy==="others"} onClick={revokeOthers}>{locale==="fa"?"خروج از سایر دستگاه‌ها":"Sign out other devices"}</Button>}</div><div className="security-list">{data.sessions.map((s)=><div className="security-row" key={s.id}><div className="security-row__icon">◉</div><div><b>{deviceName(s.userAgent,locale)}</b><p>{locale==="fa"?"آخرین فعالیت":"Last active"}: {new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(new Date(s.lastSeenAt))}</p></div><div>{s.current?<StatusLabel tone="success">{locale==="fa"?"همین دستگاه":"This device"}</StatusLabel>:<Button variant="ghost" size="sm" isLoading={busy===s.id} onClick={()=>revoke(s.id)}>{locale==="fa"?"خروج":"Sign out"}</Button>}</div></div>)}</div></section>
 {data.activity.length>0&&<section><div className="account-section-title"><h2>{locale==="fa"?"فعالیت امنیتی اخیر":"Recent security activity"}</h2></div><div className="activity-list">{data.activity.slice(0,6).map((e)=><div key={e.id}><span></span><p><b>{eventLabel(e.type,locale)}</b><small>{new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(new Date(e.occurredAt))}</small></p></div>)}</div></section>}</div>
}
function SecurityRow({title,detail,active,locale}:{title:string;detail:string;active:boolean;locale:string}){return <div className="security-row"><div className="security-row__icon">✓</div><div><b>{title}</b><p>{detail}</p></div><StatusLabel tone={active?"success":"neutral"}>{active?(locale==="fa"?"فعال":"Active"):(locale==="fa"?"غیرفعال":"Inactive")}</StatusLabel></div>}
function eventLabel(type:string,locale:string){const fa:Record<string,string>={UserAuthenticated:"ورود موفق",PasswordChanged:"رمز عبور تغییر کرد",PasswordResetCompleted:"بازیابی رمز کامل شد",SessionRevoked:"یک نشست قطع شد",OtherSessionsRevoked:"سایر نشست‌ها قطع شدند"};return locale==="fa"?(fa[type]||type):type.replace(/([A-Z])/g," $1").trim()}
